#!/usr/bin/env node
'use strict';

const Bundler = require('../bundler');
const bundler = new Bundler(__dirname);

// calc/data
let bundled = `(() => {
'use strict';
const exports = {};
`;
bundled += bundler.readModule('util.js');
bundled += bundler.readModule('data/species.js', ['util_1']);
bundled += bundler.readModule('data/types.js', ['util_1']);
bundled += bundler.readModule('data/natures.js', ['util_1']);
bundled += bundler.readModule('data/abilities.js', ['util_1']);
bundled += bundler.readModule('data/moves.js', ['util_1']);
bundled += bundler.readModule('data/items.js', ['util_1']);
bundled += bundler.readModule('data/index.js', [
  'abilities_1', 'items_1', 'moves_1', 'species_1', 'types_1', 'natures_1',
]);
bundled += `
// EXPORTS
window.calc = Object.assign(window.calc || {}, {
  Generations: exports.Generations,
  ABILITIES: exports.ABILITIES,
  ITEMS: exports.ITEMS,
  MEGA_STONES: exports.MEGA_STONES,
  MOVES: exports.MOVES,
  SPECIES: exports.SPECIES,
  NATURES: exports.NATURES,
  TYPE_CHART: exports.TYPE_CHART,
});
})();`;
bundler.bundle(bundled, 'data/production.min.js');

// calc
bundled = `(() => {
  'use strict';
  const exports = {};
  `;
bundled += bundler.readModule('util.js');
bundled += bundler.readModule('stats.js', ['util_1']);
bundled += bundler.readModule('pokemon.js', ['stats_1', 'util_1']);
bundled += bundler.readModule('field.js');
bundled += bundler.readModule('move.js', ['util_1']);
bundled += bundler.readModule('items.js', ['util_1']);
bundled += bundler.readModule('mechanics/util.js', ['util_1', 'stats_1']);
bundled += bundler.readModule('result.js', ['desc_1']);
bundled += bundler.readModule('desc.js', ['result_1', 'util_1', 'util_2']);
bundled += bundler.readModule('mechanics/gen789.js', ['util_1', 'items_1', 'result_1', 'util_2']);
bundled += bundler.readModule('mechanics/gen56.js', ['util_1', 'items_1', 'result_1', 'util_2']);
bundled += bundler.readModule('mechanics/gen4.js', ['items_1', 'result_1', 'util_1']);
bundled += bundler.readModule('mechanics/gen3.js', ['items_1', 'result_1', 'util_1']);
bundled += bundler.readModule('mechanics/gen12.js', ['items_1', 'result_1', 'util_1']);
bundled += bundler.readModule('calc.js', ['field_1', 'gen12_1', 'gen3_1', 'gen4_1', 'gen56_1', 'gen789_1']);

bundled += `
// EXPORTS
window.calc = Object.assign(window.calc || {}, {
  Field: exports.Field,
  Side: exports.Side,
  Pokemon: exports.Pokemon,
  Move: exports.Move,
  calculate: exports.calculate,
  Result: exports.Result,
  toID: exports.toID,
  STATS: exports.STATS,
  Stats: exports.Stats,
});
})();`;
bundler.bundle(bundled);
